### ISSUE TITLE
`const` accessors missing

### ISSUE THREAD

**Issue by Floessie** [janelia-arduino/Array#3]
Hi Peter,

In `Array.h` you define two accessors:

```c++
  T & operator[](const size_t index); // <-- this const is useless
  T & at(const size_t index); // <-- this, too
```

Those are only applicable to non-const instances. Please consider adding `const` variants:

```c++
  const T & operator[](size_t index) const;
  const T & at(size_t index) const;
```

Same for `data()`.

Furthermore your copy c'tor should take a `const&`:

```c++
  template <typename U, size_t N>
  Array(const Array<U,N> & values);
```

Same for `fill()` and `assign()`.

Best,
Flössie

**Comment by peterpolidoro** [comment]
Thanks! I made these changes. Please let me know if you find any more issues.
